---
- name: Check if email was changed
  assert:
    that: email != "myemail@example.com"
    msg: The email needs to be changed for Caddy to register a certificate

- name: Set variables
  set_fact:
    caddy_tarball_path: "{{ caddy_home|default('/home/caddy') }}/caddy.tar.gz"
    caddy_home: "{{ caddy_home|default('/home/caddy') }}"

- name: Create Caddy user
  user:
    name: "{{ caddy_user }}"
    system: yes
    createhome: yes
    home: "{{ caddy_home }}"

- name: Make sure {{ caddy_home }} exists
  file:
    path: "{{ caddy_home }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_user }}"
    mode: u=rwx,g=rx,o=

- name: Retrieve latest Caddy release
  uri:
    url: "https://api.github.com/repos/caddyserver/caddy/releases/latest"
    return_content: yes
    follow_redirects: safe
  changed_when: false
  register: caddy_github

# Looks like:
# {
#   ...
#   "name": "1.0.4",
#   ...
#   "tag_name": "v1.0.4",
#   ...
#   "assets": [
#     {
#       ...
#       "name": "caddy_v1.0.4_linux_amd64.tar.gz",
#       ...
#       "browser_download_url": "https://github.com/caddyserver/caddy/releases/download/v1.0.4/caddy_v1.0.4_linux_amd64.tar.gz"

- name: Find latest version number
  set_fact:
    latest_caddy_version: "{{ caddy_github.content | regex_search('(?<=tag_name\":\")([\\w\\.\\d]+)(?=\")') }}"
  # Use the caddyserver.com version, since the GitHub version lists its version as "unknown"
  #vars:
  #  query: "assets[?browser_download_url] | [?contains(@, 'linux_amd64') == `true`]"

- name: Update this role if Caddy 2 is released
  assert:
    that: "'v1' in latest_caddy_version"
    msg: "Caddy 2 was released, update this play: https://github.com/caddyserver/caddy/milestone/4"

- name: Get currently installed Caddy version
  shell: /usr/local/bin/caddy --version || echo unknown
  ignore_errors: yes
  register: current_caddy_version
  changed_when: false

# https://github.com/caddy-ansible/caddy-ansible/blob/41efc1ea66e11a79873951d1c6052e29e13cf2ba/tasks/main.yml#L42
- name: Get Caddy
  get_url:
    # Use the caddyserver.com version, since the GitHub version lists its version as "unknown"
    url: "https://caddyserver.com/download/linux/amd64?plugins=http.git&license=personal&telemetry=on"
    dest: "{{ caddy_tarball_path }}"
    force: yes
    timeout: 300
  retries: 3
  delay: 2
  register: caddy_tarball
  when: not (latest_caddy_version in current_caddy_version.stdout|default(''))

- name: Stat Caddy tarball
  stat:
    path: "{{ caddy_tarball_path }}"
  register: caddy_tarball_stat

- name: Unpack Caddy
  unarchive:
    src: "{{ caddy_tarball_path }}"
    remote_src: yes
    exclude:
      - init
      - README.txt
      - CHANGES.txt
      - LICENSES.txt
    creates: "{{ caddy_home }}/caddy"
    dest: "{{ caddy_home }}/"
    owner: "{{ caddy_user }}"
    group: "{{ caddy_user }}"
    mode: u=rx,g=rx,o=rx
  when: caddy_tarball_stat.stat.exists

- name: Remove Caddy tarball
  file:
    path: "{{ caddy_tarball_path }}"
    state: absent

- name: Check if Caddy is a known systemd service
  command: systemctl list-unit-files caddy.service
  register: caddy_service
  changed_when: false

- name: Stat Caddy binary
  stat:
    path: "{{ caddy_home }}/caddy"
  register: caddy_bin_stat

- name: Ensure Caddy is stopped before copying new binary
  service:
    name: caddy
    state: stopped
  when:
    - caddy_service.stdout is search("1 unit files listed.")
    - caddy_bin_stat.stat.exists

- name: Copy new binary into place
  copy:
    src: "{{ caddy_home }}/caddy"
    dest: /usr/local/bin/caddy
    remote_src: yes
    owner: root
    mode: u=rx,g=rx,o=rx
  when: caddy_bin_stat.stat.exists
  notify: restart caddy

- name: Remove duplicate binary
  file:
    path: "{{ caddy_home }}/caddy"
    state: absent

- name: Create Caddy directories
  file:
    path: "{{ item.0 }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_user }}"
    mode: "{{ item.1 }}"
  loop:
    - - /etc/ssl/caddy
      - u=rwx,g=rx,o=
    - - /etc/caddy
      - u=rwx,g=rwx,o=rx
    - - /etc/caddy/conf.d
      - u=rwx,g=rwx,o=rx
    - - "{{ caddy_home }}"
      - u=rwx,g=rx,o=
    - - "{{ blog_dir }}"
      - u=rwx,g=rx,o=

- name: Setup bitbucket access
  include_tasks: bitbucket_access.yaml

- name: Ensure port {{ webhook_port }} is open
  ufw:
    comment: blog webhook
    to_port: "{{ webhook_port }}"
    proto: tcp
    rule: allow

- name: Create Caddyfile
  template:
    dest: /etc/caddy/Caddyfile
    owner: "{{ caddy_user }}"
    mode: u=r,g=r,o=r
    src: Caddyfile.j2
    validate: /usr/local/bin/caddy -validate -conf %s
  notify: reload caddy

- name: Download suggested systemd service file
  get_url:
    url: "https://raw.githubusercontent.com/caddyserver/caddy/master/dist/init/linux-systemd/caddy.service"
    backup: yes
    dest: "{{ caddy_home }}/caddy.service"
    owner: "{{ caddy_user }}"
    group: "{{ caddy_user }}"
    mode: u=r,g=r,o=r
  register: caddy_service_file

- name: Make sure the service file hasn't changed since v1.0.4
  assert:
    that: caddy_service_file.checksum_src == "bb7f1043b7d29dec31dd71878c1333989a350fd7"
    msg: "Update this role's systemd caddy.service file: diff /etc/systemd/system/caddy.service /var/www/caddy.service"

- name: Remove downloaded caddy.service
  file:
    path: "{{ caddy_home }}/caddy.service"
    state: absent

- name: Install Ansible on target machine
  package:
    name: ansible
    state: present

- name: Copy systemd unit files into place
  template:
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
    #force: no
    owner: root
    group: root
    mode: u=r,g=r,o=r
  loop:
    - - caddy.service.j2
      - /etc/systemd/system/caddy.service
    - - modify_nginx.service.j2
      - /etc/systemd/system/modify_nginx.service
    - - modify_nginx.path.j2
      - /etc/systemd/system/modify_nginx.path
    - - modify_nginx.timer.j2
      - /etc/systemd/system/modify_nginx.timer
  notify:
    - reload caddy
    - restart nginx
    - reload systemd

- name: Verify systemd is okay with those files
  command: "systemd-analyze verify {{ item }}"
  loop:
    - /etc/systemd/system/caddy.service
    - /etc/systemd/system/modify_nginx.service
    - /etc/systemd/system/modify_nginx.path
    - /etc/systemd/system/modify_nginx.timer
  changed_when: false

- name: Ensure directories for modify_nginx.yaml exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
    - /etc/blog-deploy
    - /etc/ansible

- name: Copy ansible.cfg for modify_nginx.yaml into place
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    # Ansible templates files out to a temporary file on the remote machine to validate before
    # moving the temporary file into place
    # ansible-config requires the files it's passed to have one of a set of valid extensions
    #validate: /usr/bin/ansible-config view -c %s
    owner: root
    group: root
    mode: u=r,g=r,o=r
  notify: run modify_nginx.service

- name: Copy ansible playbook for modify_nginx.service.j2 into place
  template:
    src: modify_nginx.yaml.j2
    dest: /etc/blog-deploy/modify_nginx.yaml
    #force: no
    variable_start_string: "<<"
    variable_end_string: ">>"
    validate: /usr/bin/ansible-playbook --check -i 127.0.0.1, %s
    owner: root
    group: root
    mode: u=r,g=r,o=r
  notify: run modify_nginx.service

- name: Enable systemd units
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - caddy
      # Must come after caddy, as it has After= set
    - modify_nginx.path
    - modify_nginx.timer
...
