---
- name: Place backup files
  copy:
    src: "{{ item }}"
    dest: "{{ fallback_web_root|default('/var/www') }}/{{ item }}"
    owner: "{{ web_user }}"
  loop:
    - index.html

- name: Place example file
  copy:
    src: ip.txt
    dest: "{{ caddy_home|default('/var/www') }}/ip.txt"
    owner: "{{ caddy_user }}"
...
